#!/usr/bin/expect -f
set btaddr [lindex $argv 0];
spawn sudo killall rfcomm
spawn sudo rfcomm connect 0 $btaddr 1
set ids(1) $spawn_id
expect {
	"Connected /dev/rfcomm0 to $btaddr on channel 1" {
	    spawn hcitool rssi $btaddr
	    set ids(2) $spawn_id
	    expect {
		-re {RSSI return value: -?[0-9]} {
		    send -i ids(1) \003
		    exit 0
		}
	    }
	    send -i ids(1) \003
	    exit 1
	}
	"Can't connect RFCOMM socket: Host is down" {
	    exit 1
	}
}

